version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.5.0-jessie
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run test

  deploy:
    docker:
      - image: circleci/node:10.5.0-jessie
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - run: npm run deploy

  release:
    docker:
      - image: circleci/node:10.5.0-jessie
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - run: npx semantic-release

workflows:
  version: 2
  test-deploy-release:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
      - release:
          requires:
            - test
          filters:
            branches:
              only: master
